version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "echo 'Migrating DB' && python manage.py migrate && echo 'Finished migrations' && python manage.py runserver 0.0.0.0:8000"
